name: Update Blog Posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://mikesheehy.hashnode.dev/rss.xml"
